### ISSUE TITLE
Issue when requiring files with strange characters and spaces

### ISSUE THREAD

**Issue by Wbange18** [Ezzenix/AutoRequireRoblox#1]
Currently, the autocomplete fails to use brackets and quotes to address cases where characters that luau can't normally parse are used. In my case, I have a folder with a bee emoji and a space in it (ridiculous, I know,) but the extension doesn't handle this and creates a broken line. This is really problematic when this is meant to conveniently and quickly add the require line, causing unnoticed code errors in nearly every script.

https://github.com/Ezzenix/AutoRequireRoblox/assets/138693784/4ccdc0fa-d554-4f79-bf0d-151853970ea4

Notably, this could be mitigated conveniently if I could specify a start path for the require statement, as my scripts usually can see the Engine folder from _G.Engine, which would void this issue altogether. However there are currently no extension configs to my knowledge.

Thank you for your continued work on this extension!

**Comment by Ezzenix** [comment]
The extension will now index with `ReplicatedStorage["🐝 Engine"].Classes` if a folders name contains a space. Sorry for long wait.
